name: shopping_server
description: "A Shopping App using Dart and Flutter to develop project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

#======================= PACKAGES =======================#
dependencies:
  flutter:
    sdk: flutter

# Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

# Fonts
  google_fonts: ^6.2.1

# State Management
  get: ^4.6.6
  get_storage: ^2.1.1

# Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.2
  connectivity_plus: ^6.0.3
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.0

# Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

# Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^3.5.0
  firebase_storage: ^12.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


#======================= ASSETS =======================#
flutter:
  uses-material-design: true

  #----------------------- LOCAL ASSETS ----------------------#
  assets:
    - assets/logos/
    - assets/images/
    - assets/images/banners/
    - assets/images/animation/
    - assets/images/email_verification/
    - assets/images/products/
    - assets/images/personalization/
    - assets/icons/
    - assets/icons/brand_icons/
    - assets/icons/brand_icons/colored/
    - assets/icons/brand_icons/dark/
    - assets/icons/brand_icons/light/
    - assets/icons/categories_icons/
    - assets/icons/payments/

  #----------------------- LOCAL FONTS -----------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic