// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoTbDco9SeKA49jJT1H4UMV8T1Aie-fcA',
    appId: '1:274356471479:android:38a010f3d18a51279fef32',
    messagingSenderId: '274356471479',
    projectId: 'shopping-server-fe8a3',
    storageBucket: 'shopping-server-fe8a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMLFas7Lvedkck7dsTtOoGhnWN6Co_jYs',
    appId: '1:274356471479:ios:c0f38924d4b0b2b89fef32',
    messagingSenderId: '274356471479',
    projectId: 'shopping-server-fe8a3',
    storageBucket: 'shopping-server-fe8a3.appspot.com',
    androidClientId: '274356471479-66c4u12tl9fhd9ukun7rr26mh9pfej66.apps.googleusercontent.com',
    iosClientId: '274356471479-8k03hgepdlj97fg3ulpr29fbga9u6aof.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingServer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ908cG8paRIX4LjN6YU7VCeXuUs2EWFs',
    appId: '1:274356471479:web:ed21cde518236fb09fef32',
    messagingSenderId: '274356471479',
    projectId: 'shopping-server-fe8a3',
    authDomain: 'shopping-server-fe8a3.firebaseapp.com',
    storageBucket: 'shopping-server-fe8a3.appspot.com',
  );

}